#!/bin/sh -e
# Confluence startup script
#chkconfig: 2345 80 05
#description: Confluence

### BEGIN INIT INFO
# Provides:         atlassian_confluence
# Required-Start:   $remote_fs $syslog $network
# Required-Stop:    $remote_fs $syslog $network
# Default-Start:    2 3 4 5
# Default-Stop:     0 1 6
# Short-Description: Start Confluence Wiki at boot
# Description: Controls the Atlassian CONFLUENCE application
### END INIT INFO


 
# Define some variables
# Name of app ( JIRA, Confluence, etc )
APP=confluence
# Name of the user to run as
USER=atlassian
# Location of application's bin directory
CATALINA_HOME=/opt/atlassian/confluence/current
# Location of Java JDK
 
case "$1" in
  # Start command
  start)
    echo "Starting $APP"
    /bin/su -m $USER -c "$CATALINA_HOME/bin/startup.sh &> /dev/null"
    ;;
  # Stop command
  stop)
    echo "Stopping $APP"
    /bin/su -m $USER -c "$CATALINA_HOME/bin/shutdown.sh &> /dev/null"
    echo "$APP stopped successfully"
    ;;
   # Restart command
   restart)
        $0 stop
        sleep 5
        $0 start
        ;;
  *)
    echo "Usage: /etc/init.d/$APP {start|restart|stop}"
    exit 1
    ;;
esac
 
exit 0
